version: "3.3"

services:
  ms_auth-test: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms_authentication-test
    env_file:
      - ./variables.env
    ports:
      - "4000:4000"
      - "5672:5672"
      - "587:587"
    command: npm start
    networks:
      - ucar-network

networks:
  ucar-network:
    external: true
 